'use client';
import Head from 'next/head';
import React, { useState } from 'react';
import Header from '@/components/Header/header';
import Footer from '@/components/Footer/footer';
import { MapContainer, Marker, Popup, TileLayer } from 'react-leaflet';

export default function Map() {
  return (
    <div>
      <Header />
      <div>
        <Head>
          <title>VPI</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <MapContainer
          className="w-1/2"
          center={[51.505, -0.09]}
          zoom={13}
          scrollWheelZoom={false}
        >
          <TileLayer
            attribution='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
            url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
          />
          <Marker position={[51.515, -0.09]}>
            <Popup>
              A pretty CSS3 popup1. <br /> Easily customizable.
            </Popup>
          </Marker>
        </MapContainer>
      </div>
      <Footer />
    </div>
  );
}
