'use client';
// import Head from 'next/head';
// import React from 'react';
// import Header from '@/components/Header/header';
// import Footer from '@/components/Footer/footer';
// import { MapContainer, Marker, Popup, TileLayer } from 'react-leaflet';

// export default function Map() {
//   return (
//     <div>
//       <Header />
//       <div>
//         <Head>
//           <title>VPI</title>
//           <meta name="description" content="Generated by create next app" />
//           <link rel="icon" href="/favicon.ico" />
//         </Head>
//         <Map></Map>
//       </div>
//       <Footer />
//     </div>
//   );
// }

import dynamic from 'next/dynamic';

function HomePage() {
  const Map = dynamic(
    () => import('@/components/Map/Map'), // replace '@components/map' with your component's location
    { ssr: false } // This line is important. It's what prevents server-side render
  );
  return <Map />;
}

export default HomePage;
