export interface Fortification {
  id: number;
  fortificationName: string;
  attackBonus: number;
  healthBonus: number;
  attackHorseman: number;
  attackSwordsman: number;
  attackSpearman: number;
  defenseHorseman: number;
  defenseSword: number;
  defenseSpear: number;
}

export const fortificationData: Fortification[] = [
  {
    id: 1000,
    fortificationName: 'Без укреплений',
    attackBonus: 0,
    healthBonus: 0,
    attackHorseman: 1,
    attackSwordsman: 1,
    attackSpearman: 1,
    defenseHorseman: 1,
    defenseSword: 1,
    defenseSpear: 1,
  },
  {
    id: 1001,
    fortificationName: 'Барикады из повозок',
    attackBonus: 0,
    healthBonus: 3,
    attackHorseman: 1.1,
    attackSwordsman: 1.1,
    attackSpearman: 1.1,
    defenseHorseman: 1.1,
    defenseSword: 1.1,
    defenseSpear: 1.1,
  },
  {
    id: 1002,
    fortificationName: 'Частокол',
    attackBonus: 0,
    healthBonus: 5,
    attackHorseman: 1.2,
    attackSwordsman: 1.2,
    attackSpearman: 1.2,
    defenseHorseman: 1.2,
    defenseSword: 1.2,
    defenseSpear: 1.2,
  },
  {
    id: 1003,
    fortificationName: 'Каменная стена 1 ур',
    attackBonus: 3,
    healthBonus: 10,
    attackHorseman: 1.3,
    attackSwordsman: 1.3,
    attackSpearman: 1.3,
    defenseHorseman: 1.3,
    defenseSword: 1.3,
    defenseSpear: 1.3,
  },
  {
    id: 1003,
    fortificationName: 'Каменная стена 2 ур',
    attackBonus: 6,
    healthBonus: 15,
    attackHorseman: 1.4,
    attackSwordsman: 1.4,
    attackSpearman: 1.4,
    defenseHorseman: 1.4,
    defenseSword: 1.4,
    defenseSpear: 1.4,
  },
  {
    id: 1004,
    fortificationName: 'Каменная стена 3 ур',
    attackBonus: 9,
    healthBonus: 20,
    attackHorseman: 1.5,
    attackSwordsman: 1.5,
    attackSpearman: 1.5,
    defenseHorseman: 1.5,
    defenseSword: 1.5,
    defenseSpear: 1.5,
  },
  {
    id: 1100,
    fortificationName: 'Равнина',
    attackBonus: 0,
    healthBonus: 0,
    attackHorseman: 1.1,
    attackSwordsman: 1,
    attackSpearman: 1,
    defenseHorseman: 1.1,
    defenseSword: 1,
    defenseSpear: 1,
  },
  {
    id: 1101,
    fortificationName: 'Лес',
    attackBonus: 0,
    healthBonus: 0,
    attackHorseman: 0.5,
    attackSwordsman: 1,
    attackSpearman: 0.5,
    defenseHorseman: 1,
    defenseSword: 1,
    defenseSpear: 1,
  },
  {
    id: 1102,
    fortificationName: 'Болото',
    attackBonus: 0.5,
    healthBonus: 0.5,
    attackHorseman: 0.5,
    attackSwordsman: 0.5,
    attackSpearman: 0.5,
    defenseHorseman: 0.5,
    defenseSword: 0.5,
    defenseSpear: 0.5,
  },
  {
    id: 1103,
    fortificationName: 'Горы',
    attackBonus: 0,
    healthBonus: 0,
    attackHorseman: 0.5,
    attackSwordsman: 1,
    attackSpearman: 1,
    defenseHorseman: 1,
    defenseSword: 1,
    defenseSpear: 1,
  },
];
