export interface Hero {
  id: number;
  heroName: string;
  attackBonus: number;
  healthBonus: number;
  moralityBonus: number;
  attackHorseman: number;
  attackSwordsman: number;
  attackSpearman: number;
  defenseHorseman: number;
  defenseSword: number;
  defenseSpear: number;
}

export const heroesData: Hero[] = [
  {
    id: 100,
    heroName: 'Командир',
    attackBonus: 0,
    healthBonus: 0,
    moralityBonus: 0,
    attackHorseman: 1,
    attackSwordsman: 1,
    attackSpearman: 1,
    defenseHorseman: 1,
    defenseSword: 1,
    defenseSpear: 1,
  },
  {
    id: 101,
    heroName: 'Морс Мартелл',
    attackBonus: 0,
    healthBonus: 0,
    moralityBonus: 12,
    attackHorseman: 1,
    attackSwordsman: 1,
    attackSpearman: 1,
    defenseHorseman: 1,
    defenseSword: 1.2,
    defenseSpear: 1.2,
  },
  {
    id: 102,
    heroName: 'Беррик Сантагар',
    attackBonus: 10,
    healthBonus: 0,
    moralityBonus: 0,
    attackHorseman: 1.5,
    attackSwordsman: 1,
    attackSpearman: 1,
    defenseHorseman: 1,
    defenseSword: 1,
    defenseSpear: 1,
  },
  {
    id: 103,
    heroName: 'Нимерия',
    attackBonus: 8,
    healthBonus: 0,
    moralityBonus: 0,
    attackHorseman: 1.2,
    attackSwordsman: 1.2,
    attackSpearman: 1.2,
    defenseHorseman: 1,
    defenseSword: 1,
    defenseSpear: 1,
  },
  {
    id: 104,
    heroName: 'Эдрик Виль',
    attackBonus: 8,
    healthBonus: 0,
    moralityBonus: 12,
    attackHorseman: 1,
    attackSwordsman: 1,
    attackSpearman: 1,
    defenseHorseman: 1,
    defenseSword: 1,
    defenseSpear: 1,
  },
  {
    id: 105,
    heroName: 'Робар Виль',
    attackBonus: 6,
    healthBonus: 0,
    moralityBonus: 8,
    attackHorseman: 1,
    attackSwordsman: 1,
    attackSpearman: 1,
    defenseHorseman: 1.1,
    defenseSword: 1.1,
    defenseSpear: 1,
  },
  {
    id: 106,
    heroName: 'Дарон Виль',
    attackBonus: 10,
    healthBonus: 0,
    moralityBonus: 8,
    attackHorseman: 1,
    attackSwordsman: 1.2,
    attackSpearman: 1,
    defenseHorseman: 1,
    defenseSword: 1,
    defenseSpear: 1.2,
  },
  {
    id: 107,
    heroName: 'Вориан Дейн',
    attackBonus: 10,
    healthBonus: 0,
    moralityBonus: 0,
    attackHorseman: 1,
    attackSwordsman: 1,
    attackSpearman: 1,
    defenseHorseman: 1,
    defenseSword: 1,
    defenseSpear: 1,
  },
  {
    id: 108,
    heroName: 'Эдриан Дейн',
    attackBonus: 4,
    healthBonus: 0,
    moralityBonus: 4,
    attackHorseman: 1,
    attackSwordsman: 1,
    attackSpearman: 1,
    defenseHorseman: 1.3,
    defenseSword: 1.3,
    defenseSpear: 1,
  },
  {
    id: 109,
    heroName: 'Давос Дейн',
    attackBonus: 4,
    healthBonus: 0,
    moralityBonus: 0,
    attackHorseman: 1.3,
    attackSwordsman: 1.3,
    attackSpearman: 1.2,
    defenseHorseman: 1,
    defenseSword: 1,
    defenseSpear: 1,
  },
  {
    id: 110,
    heroName: 'Гаррисон Фаулер',
    attackBonus: 0,
    healthBonus: 0,
    moralityBonus: 2,
    attackHorseman: 1,
    attackSwordsman: 1,
    attackSpearman: 1,
    defenseHorseman: 1,
    defenseSword: 1,
    defenseSpear: 1,
  },
  {
    id: 111,
    heroName: 'Франклин Фаулер',
    attackBonus: 0,
    healthBonus: 0,
    moralityBonus: 0,
    attackHorseman: 1.7,
    attackSwordsman: 1.7,
    attackSpearman: 1.7,
    defenseHorseman: 1,
    defenseSword: 1,
    defenseSpear: 1,
  },
  {
    id: 112,
    heroName: 'Феррис Фаулер',
    attackBonus: 0,
    healthBonus: 0,
    moralityBonus: 0,
    attackHorseman: 1,
    attackSwordsman: 1,
    attackSpearman: 1,
    defenseHorseman: 1.3,
    defenseSword: 1.3,
    defenseSpear: 1.3,
  },
  {
    id: 113,
    heroName: 'Йорик V Айронвуд',
    attackBonus: 0,
    healthBonus: 0,
    moralityBonus: 4,
    attackHorseman: 1,
    attackSwordsman: 1,
    attackSpearman: 1,
    defenseHorseman: 1.4,
    defenseSword: 1.4,
    defenseSpear: 1,
  },
  {
    id: 114,
    heroName: 'Йормунд Айронвуд',
    attackBonus: 10,
    healthBonus: 0,
    moralityBonus: 10,
    attackHorseman: 1,
    attackSwordsman: 1,
    attackSpearman: 1.5,
    defenseHorseman: 1,
    defenseSword: 1,
    defenseSpear: 1,
  },
  {
    id: 115,
    heroName: 'Борик из Гринбельта',
    attackBonus: 0,
    healthBonus: 0,
    moralityBonus: 0,
    attackHorseman: 1,
    attackSwordsman: 1.5,
    attackSpearman: 1,
    defenseHorseman: 1,
    defenseSword: 1,
    defenseSpear: 1,
  },
  {
    id: 116,
    heroName: 'Бенедикт Блэкмонт',
    attackBonus: 14,
    healthBonus: 0,
    moralityBonus: 6,
    attackHorseman: 1.4,
    attackSwordsman: 1.4,
    attackSpearman: 1,
    defenseHorseman: 1,
    defenseSword: 1,
    defenseSpear: 1,
  },
  {
    id: 117,
    heroName: 'Бандикут Блэкмонт',
    attackBonus: 0,
    healthBonus: 0,
    moralityBonus: 0,
    attackHorseman: 1,
    attackSwordsman: 1,
    attackSpearman: 1,
    defenseHorseman: 1,
    defenseSword: 1,
    defenseSpear: 1.2,
  },
  {
    id: 118,
    heroName: 'Бафомет Сэнд',
    attackBonus: 10,
    healthBonus: 0,
    moralityBonus: 0,
    attackHorseman: 1,
    attackSwordsman: 1.5,
    attackSpearman: 1,
    defenseHorseman: 1,
    defenseSword: 1,
    defenseSpear: 1,
  },

  {
    id: 119,
    heroName: 'Требор Джордейн',
    attackBonus: 4,
    healthBonus: 0,
    moralityBonus: 4,
    attackHorseman: 1,
    attackSwordsman: 1.4,
    attackSpearman: 1,
    defenseHorseman: 1,
    defenseSword: 1,
    defenseSpear: 1,
  },
  {
    id: 120,
    heroName: 'Найра Толанд',
    attackBonus: 6,
    healthBonus: 0,
    moralityBonus: 6,
    attackHorseman: 1,
    attackSwordsman: 1,
    attackSpearman: 1.4,
    defenseHorseman: 1,
    defenseSword: 1,
    defenseSpear: 1,
  },
  {
    id: 121,
    heroName: 'Корвин Толанд',
    attackBonus: 4,
    healthBonus: 0,
    moralityBonus: 4,
    attackHorseman: 1,
    attackSwordsman: 1,
    attackSpearman: 1,
    defenseHorseman: 1.3,
    defenseSword: 1.3,
    defenseSpear: 1,
  },
  {
    id: 122,
    heroName: 'Люцифер Драйленд',
    attackBonus: 4,
    healthBonus: 0,
    moralityBonus: 2,
    attackHorseman: 1,
    attackSwordsman: 1,
    attackSpearman: 1,
    defenseHorseman: 1,
    defenseSword: 1,
    defenseSpear: 1,
  },
  {
    id: 123,
    heroName: 'Герольд Драйленд',
    attackBonus: 0,
    healthBonus: 0,
    moralityBonus: 0,
    attackHorseman: 1.6,
    attackSwordsman: 1,
    attackSpearman: 1.6,
    defenseHorseman: 1,
    defenseSword: 1,
    defenseSpear: 1,
  },
  {
    id: 124,
    heroName: 'Дорея Драйленд',
    attackBonus: 0,
    healthBonus: 0,
    moralityBonus: 6,
    attackHorseman: 1,
    attackSwordsman: 1,
    attackSpearman: 1,
    defenseHorseman: 1,
    defenseSword: 1.6,
    defenseSpear: 1,
  },
  //   Гарольд Дальт 46 лет
  // Мораль 5, бонус в атаке по всадникам +0.5

  // Ивар Дальт 29 лет
  // Мораль 5, бонус к атаке по копейщикам + 0.5

  // Хазер Дальт 28 лет
  // Мораль 5, бонус в атаке по мечникам +0.5
  {
    id: 125,
    heroName: ' Гарольд Дальт',
    attackBonus: 0,
    healthBonus: 0,
    moralityBonus: 10,
    attackHorseman: 1.5,
    attackSwordsman: 1,
    attackSpearman: 1,
    defenseHorseman: 1,
    defenseSword: 1,
    defenseSpear: 1,
  },
  {
    id: 126,
    heroName: 'Ивар Дальт',
    attackBonus: 0,
    healthBonus: 0,
    moralityBonus: 10,
    attackHorseman: 1,
    attackSwordsman: 1,
    attackSpearman: 1.5,
    defenseHorseman: 1,
    defenseSword: 1,
    defenseSpear: 1,
  },
  {
    id: 127,
    heroName: 'Хазер Дальт',
    attackBonus: 0,
    healthBonus: 0,
    moralityBonus: 10,
    attackHorseman: 1,
    attackSwordsman: 1.5,
    attackSpearman: 1,
    defenseHorseman: 1,
    defenseSword: 1,
    defenseSpear: 1,
  },
  // {
  //   id: 997,
  //   heroName: 'Тирион Клиган',
  //   attackBonus: 20,
  //   healthBonus: 0,
  //   moralityBonus: 0,
  //   attackHorseman: 1,
  //   attackSwordsman: 1,
  //   attackSpearman: 1,
  //   defenseHorseman: 1,
  //   defenseSword: 1,
  //   defenseSpear: 1,
  // },
  // {
  //   id: 998,
  //   heroName: 'Григор Аррен',
  //   attackBonus: 0,
  //   healthBonus: 0,
  //   moralityBonus: 0,
  //   attackHorseman: 1,
  //   attackSwordsman: 2,
  //   attackSpearman: 1,
  //   defenseHorseman: 1,
  //   defenseSword: 1,
  //   defenseSpear: 1,
  // },
  // {
  //   id: 999,
  //   heroName: 'Эддарт Ланнистер',
  //   attackBonus: 0,
  //   healthBonus: 0,
  //   moralityBonus: 0,
  //   attackHorseman: 1,
  //   attackSwordsman: 1,
  //   attackSpearman: 1,
  //   defenseHorseman: 1,
  //   defenseSword: 1.5,
  //   defenseSpear: 1.5,
  // },
];
