export enum Weapon {
  sword,
  spear,
}

export interface squadUnitOld {
  id: number;
  name: string;
  horse: boolean;
  bow: boolean;
  weapon: Weapon;
  attack: number;
  distanceAttack: number;
  health: number;
  morality: number;
  size: number;
  price: number;
  attackHorseman: number;
  attackSwordsman: number;
  attackSpearman: number;
  defenseHorseman: number;
  defenseSword: number;
  defenseSpear: number;
  ready: boolean;
  iron: number;
  tree: number;
  skins: number;
  horses: number;
}

export interface UnitData {
  name: string;
  subRows: squadUnitOld[];
}
[];

export const unitsData: UnitData[] = [
  {
    name: 'Конница',

    subRows: [
      // {
      //   id: 0,
      //   name: 'Не задано',
      //   horse: true,
      //   bow: false,
      //   weapon: Weapon.sword,
      //   attack: 0,
      //   distanceAttack: 0,
      //   health: 0,
      //   morality: 0,
      //   size: 3,
      //   price:1,
      //   attackHorseman: 1,
      //   attackSwordsman: 1,
      //   attackSpearman: 1,
      //   defenseHorseman: 1,
      //   defenseSword: 1,
      //   defenseSpear: 1,
      // ready: true,
      //       //     iron: 11,
      //     tree: 22,
      //     skins: 33,
      //     horses: 44
      //
      // },
      {
        id: 1,
        name: 'Конный Рыцарь',
        horse: true,
        bow: false,
        weapon: Weapon.sword,
        attack: 60,
        distanceAttack: 0,
        health: 600,
        morality: 50,
        size: 3,
        price: 32,
        attackHorseman: 1.5,
        attackSwordsman: 2,
        attackSpearman: 1.5,
        defenseHorseman: 1,
        defenseSword: 1,
        defenseSpear: 1,
        ready: true,
        iron: 28,
        tree: 2,
        skins: 2,
        horses: 1,
      },
      {
        id: 2,
        name: 'Конный Мечник',
        horse: true,
        bow: false,
        weapon: Weapon.sword,
        attack: 50,
        distanceAttack: 0,
        health: 400,
        morality: 30,
        size: 3,
        price: 24,
        attackHorseman: 1.5,
        attackSwordsman: 1.5,
        attackSpearman: 1.5,
        defenseHorseman: 1,
        defenseSword: 1,
        defenseSpear: 1,
        ready: true,
        iron: 8,
        tree: 3,
        skins: 4,
        horses: 1,
      },
      {
        id: 3,
        name: 'Конный Лучник???',
        horse: true,
        bow: true,
        weapon: Weapon.sword,
        attack: 25,
        distanceAttack: 15,
        health: 400,
        morality: 25,
        size: 3,
        price: 2,
        attackHorseman: 1,
        attackSwordsman: 1,
        attackSpearman: 1,
        defenseHorseman: 1,
        defenseSword: 1,
        defenseSpear: 1,
        ready: true,
        iron: 2,
        tree: 1,
        skins: 0,
        horses: 1,
      },
    ],
  },
  {
    name: 'Пехота',

    subRows: [
      {
        id: 4,
        name: 'Копейщик',
        horse: false,
        bow: false,
        weapon: Weapon.spear,
        attack: 40,
        distanceAttack: 0,
        health: 300,
        morality: 40,
        size: 2,
        price: 12,
        attackHorseman: 1.5,
        attackSwordsman: 1,
        attackSpearman: 1,
        defenseHorseman: 2,
        defenseSword: 1,
        defenseSpear: 1,
        ready: true,
        iron: 5,
        tree: 6,
        skins: 4,
        horses: 0,
      },
      {
        id: 5,
        name: 'Мечник',
        horse: false,
        bow: false,
        weapon: Weapon.sword,
        attack: 40,
        distanceAttack: 0,
        health: 300,
        morality: 40,
        size: 2,
        price: 13,
        attackHorseman: 1,
        attackSwordsman: 1,
        attackSpearman: 1.5,
        defenseHorseman: 1,
        defenseSword: 1,
        defenseSpear: 1.5,
        ready: true,
        iron: 8,
        tree: 3,
        skins: 4,
        horses: 0,
      },
      {
        id: 6,
        name: 'Лучник',
        horse: false,
        bow: true,
        weapon: Weapon.sword,
        attack: 20,
        distanceAttack: 20,
        health: 200,
        morality: 20,
        size: 2,
        price: 15,
        attackHorseman: 1,
        attackSwordsman: 1,
        attackSpearman: 1,
        defenseHorseman: 1,
        defenseSword: 1,
        defenseSpear: 1,
        ready: true,
        iron: 2,
        tree: 1,
        skins: 0,
        horses: 0,
      },
      {
        id: 7,
        name: 'Одичалый',
        horse: false,
        bow: false,
        weapon: Weapon.spear,
        attack: 25,
        distanceAttack: 0,
        health: 400,
        morality: 30,
        size: 2,
        price: 9,
        attackHorseman: 1.3,
        attackSwordsman: 1,
        attackSpearman: 1,
        defenseHorseman: 1.7,
        defenseSword: 1,
        defenseSpear: 1,
        ready: true,
        iron: 1,
        tree: 1,
        skins: 1,
        horses: 0,
      },
      {
        id: 8,
        name: 'Вольные Кланы',
        horse: false,
        bow: false,
        weapon: Weapon.sword,
        attack: 50,
        distanceAttack: 0,
        health: 300,
        morality: 35,
        size: 2,
        price: 15,
        attackHorseman: 1,
        attackSwordsman: 1.4,
        attackSpearman: 1,
        defenseHorseman: 0.7,
        defenseSword: 0.7,
        defenseSpear: 1,
        ready: true,
        iron: 10,
        tree: 0,
        skins: 3,
        horses: 0,
      },
      {
        id: 9,
        name: 'Ополченец',
        horse: false,
        bow: false,
        weapon: Weapon.spear,
        attack: 25,
        distanceAttack: 0,
        health: 250,
        morality: 25,
        size: 2,
        price: 4,
        attackHorseman: 1.1,
        attackSwordsman: 1,
        attackSpearman: 1,
        defenseHorseman: 1.3,
        defenseSword: 1,
        defenseSpear: 1,
        ready: true,
        iron: 0,
        tree: 0,
        skins: 0,
        horses: 0,
      },
      {
        id: 10,
        name: 'Безупречный',
        horse: false,
        bow: false,
        weapon: Weapon.spear,
        attack: 45,
        distanceAttack: 0,
        health: 400,
        morality: 85,
        size: 2,
        price: 25,
        attackHorseman: 1.8,
        attackSwordsman: 1.5,
        attackSpearman: 1,
        defenseHorseman: 2,
        defenseSword: 1.5,
        defenseSpear: 1,
        ready: true,
        iron: 8,
        tree: 4,
        skins: 4,
        horses: 0,
      },
      {
        id: 11,
        name: 'Пеший Рыцарь???', // не надо кормить коня
        horse: false,
        bow: false,
        weapon: Weapon.sword,
        attack: 60,
        distanceAttack: 0,
        health: 400,
        morality: 50,
        size: 2,
        price: 22,
        attackHorseman: 1,
        attackSwordsman: 1,
        attackSpearman: 1,
        defenseHorseman: 1,
        defenseSword: 1.5,
        defenseSpear: 1.5,
        ready: true,
        iron: 28,
        tree: 2,
        skins: 2,
        horses: 0,
      },
      {
        id: 12,
        name: 'Моряк ???',
        horse: false,
        bow: false,
        weapon: Weapon.sword,
        attack: 35,
        distanceAttack: 0,
        health: 350,
        morality: 40,
        size: 2,
        price: 12,
        attackHorseman: 0.8,
        attackSwordsman: 1.4,
        attackSpearman: 1,
        defenseHorseman: 1,
        defenseSword: 1.4,
        defenseSpear: 1,
        ready: true,
        iron: 3,
        tree: 0,
        skins: 0,
        horses: 0,
      },
      {
        id: 13,
        name: 'Арбалетчик???',
        horse: false,
        bow: true,
        weapon: Weapon.sword,
        attack: 20,
        distanceAttack: 25,
        health: 200,
        morality: 20,
        size: 2,
        price: 15,
        attackHorseman: 1,
        attackSwordsman: 1,
        attackSpearman: 1,
        defenseHorseman: 1,
        defenseSword: 1,
        defenseSpear: 1,
        ready: true,
        iron: 9,
        tree: 4,
        skins: 4,
        horses: 0,
      },
      {
        id: 30,
        name: 'Спешенный Рыцарь',
        horse: false,
        bow: false,
        weapon: Weapon.sword,
        attack: 60,
        distanceAttack: 0,
        health: 400,
        morality: 50,
        size: 2,
        price: 32,
        attackHorseman: 1,
        attackSwordsman: 1,
        attackSpearman: 1,
        defenseHorseman: 1,
        defenseSword: 1.5,
        defenseSpear: 1.5,
        ready: true,
        iron: 28,
        tree: 2,
        skins: 2,
        horses: 1,
      },
      {
        id: 31,
        name: 'Спешенный Мечник',
        horse: false,
        bow: false,
        weapon: Weapon.sword,
        attack: 40,
        distanceAttack: 0,
        health: 300,
        morality: 30,
        size: 2,
        price: 24,
        attackHorseman: 1,
        attackSwordsman: 1,
        attackSpearman: 1.5,
        defenseHorseman: 1,
        defenseSword: 1,
        defenseSpear: 1.5,
        ready: true,
        iron: 8,
        tree: 3,
        skins: 4,
        horses: 1,
      },
      {
        id: 32,
        name: 'Спешенный Лучник???',
        horse: false,
        bow: true,
        weapon: Weapon.sword,
        attack: 20,
        distanceAttack: 20,
        health: 200,
        morality: 20,
        size: 2,
        price: 15,
        attackHorseman: 1,
        attackSwordsman: 1,
        attackSpearman: 1,
        defenseHorseman: 1,
        defenseSword: 1,
        defenseSpear: 1,
        ready: true,
        iron: 2,
        tree: 1,
        skins: 0,
        horses: 1,
      },
    ],
  },
  {
    name: 'Флот',

    subRows: [
      {
        id: 114,
        name: 'Пинас',
        horse: false,
        bow: false,
        weapon: Weapon.spear,
        attack: 35,
        distanceAttack: 0,
        health: 350,
        morality: 40,
        size: 2,
        price: 2,
        attackHorseman: 1,
        attackSwordsman: 1,
        attackSpearman: 1,
        defenseHorseman: 1.2,
        defenseSword: 1.5,
        defenseSpear: 2,
        ready: true,
        iron: 0,
        tree: 0,
        skins: 0,
        horses: 0,
      },
      {
        id: 115,
        name: 'Ладья',
        horse: false,
        bow: false,
        weapon: Weapon.spear,
        attack: 35,
        distanceAttack: 0,
        health: 350,
        morality: 40,
        size: 2,
        price: 2,
        attackHorseman: 1,
        attackSwordsman: 1,
        attackSpearman: 1.5,
        defenseHorseman: 1,
        defenseSword: 1.2,
        defenseSpear: 1.5,
        ready: true,
        iron: 0,
        tree: 0,
        skins: 0,
        horses: 0,
      },
      {
        id: 116,
        name: 'Драккар',
        horse: false,
        bow: false,
        weapon: Weapon.spear,
        attack: 35,
        distanceAttack: 0,
        health: 350,
        morality: 40,
        size: 2,
        price: 2,
        attackHorseman: 1.5,
        attackSwordsman: 1.2,
        attackSpearman: 1.1,
        defenseHorseman: 1,
        defenseSword: 1.1,
        defenseSpear: 1.1,
        ready: true,
        iron: 0,
        tree: 0,
        skins: 0,
        horses: 0,
      },
      {
        id: 117,
        name: 'Баркалон',
        horse: false,
        bow: false,
        weapon: Weapon.spear,
        attack: 35,
        distanceAttack: 0,
        health: 350,
        morality: 40,
        size: 2,
        price: 2,
        attackHorseman: 1.5,
        attackSwordsman: 1,
        attackSpearman: 1,
        defenseHorseman: 1.2,
        defenseSword: 1,
        defenseSpear: 1,
        ready: true,
        iron: 0,
        tree: 0,
        skins: 0,
        horses: 0,
      },
      {
        id: 118,
        name: 'Галера',
        horse: false,
        bow: false,
        weapon: Weapon.spear,
        attack: 35,
        distanceAttack: 0,
        health: 350,
        morality: 40,
        size: 2,
        price: 2,
        attackHorseman: 1,
        attackSwordsman: 1.2,
        attackSpearman: 1.5,
        defenseHorseman: 1,
        defenseSword: 1.2,
        defenseSpear: 1,
        ready: true,
        iron: 0,
        tree: 0,
        skins: 0,
        horses: 0,
      },
      {
        id: 119,
        name: 'Галеон',
        horse: false,
        bow: false,
        weapon: Weapon.spear,
        attack: 35,
        distanceAttack: 0,
        health: 350,
        morality: 40,
        size: 2,
        price: 2,
        attackHorseman: 1,
        attackSwordsman: 2,
        attackSpearman: 1.2,
        defenseHorseman: 1,
        defenseSword: 1.2,
        defenseSpear: 1.2,
        ready: true,
        iron: 0,
        tree: 0,
        skins: 0,
        horses: 0,
      },
    ],
  },
];
